#!/bin/bash

##
## ONLY RUN THIS VIA TOX
##

#set -x

envdir="$1"
shift
scripts="$*"
if [ -z "$scripts" ]
then
    scripts=$(ack-grep -L SKIP tests/test*.sh)
    if [ -z "$scripts" ]
    then
        echo "Could not find any test scripts to run" 1>&2
        exit 1
    fi
fi

# Force the tox virtualenv to be active.  
#
# Since this script runs from within a separate shell created by tox,
# the name of the virtualenv (in $VIRTUAL_ENV) is inherited, but the
# shell functions and other settings created by the activate script
# are *not* inherited.
#
source "$envdir/bin/activate"

SHELL=bash

# Run the test scripts with a little formatting around them to make it
# easier to find where each script output starts.
for test_script in $scripts
do
        export test_shell=$(which bash)

        echo
        echo '********************************************************************************'
        echo "Running $test_script"
        echo "  VIRTUAL_ENV=$VIRTUAL_ENV"
        echo "  VIRTUALENVWRAPPER_PYTHON=$VIRTUALENVWRAPPER_PYTHON"
        echo "    $($VIRTUALENVWRAPPER_PYTHON -V 2>&1)"
        echo "  PYTHONPATH=$PYTHONPATH"
        echo "  SHELL=bash"
        echo
        export SHUNIT_PARENT="$test_script"
        bash $test_script || exit 1
        echo
done

exit 0
